### ISSUE TITLE
DBSchema & SampleState

### ISSUE THREAD

**Issue by BCrawfordScott** [Brothman/MortalNote#1]
+ Schema: 
- [x] Add user_id to tags: Tags belong to specific users and aren't transferable between users(initially anyway, maybe as a bonus)
- [x]  Add formatted_text column to Notes table: Your notes table will want to have a couple more columns to account for the rich text editing.  Rich text is achieved through html formatting, but html formatting is simply a string with html elements and style rules.  See this example that has two text columns but one is 'body' and the other is 'body plain': https://github.com/ommish/Omninote/blob/master/db/schema.rb

+ SampleState: 
- [x] Put together sample state ASAP!  Remember it doesn't need to be perfect, just a first draft, but it's important to start organizing the shape of this data now.

**Comment by Brothman** [comment]
1. Added user_id to tags.
2. I added a `content_plain` and `flag_id` column to the Notes Database Schema. However, I did so by copy and paste, rather than full understanding of Rich Text Editing (RTE). I have done a brief search for tools like Quill and Draft to help implement RTE but I have not studied the material yet. From your description, I am led to believe that RTE is simply an HTML String like `"<p> Hello </p>"`that we then apply CSS styles to like `p { font-style: italic }` whenever we have selected the flag for `i` or typed in `CMD-I`. I do wonder if I need a way of holding multiple selected flags. In such a case, do I need a joins table between flags and notes for selected flags?
3. Sample state design document created.
